class PatientRegistrationModel {
  final String patientId;
  final String name;
  final String dob;
  final String gender;
  final String phone;
  final String address;
  final String bloodGroup;
  final String insuranceProvider;
  final String emergencyContact;
  final double? weight;
  final String? bloodPressure;

  const PatientRegistrationModel({
    required this.patientId,
    required this.name,
    required this.dob,
    required this.gender,
    required this.phone,
    required this.address,
    required this.bloodGroup,
    required this.insuranceProvider,
    required this.emergencyContact,
    this.weight,
    this.bloodPressure,
  });

  factory PatientRegistrationModel.createEmpty({required String autogeneratedId}) {
    return PatientRegistrationModel(
      patientId: autogeneratedId,
      name: '',
      dob: '',
      gender: 'Male',
      phone: '',
      address: '',
      bloodGroup: 'A+',
      insuranceProvider: '',
      emergencyContact: '',
      weight: null,
      bloodPressure: null,
    );
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> map = {
      'patientId': patientId,
      'name': name,
      'dob': dob,
      'gender': gender,
      'phone': phone,
      'address': address,
      'bloodGroup': bloodGroup,
      'insuranceProvider': insuranceProvider,
      'emergencyContact': emergencyContact,
    };
    if (weight != null) {
      map['weight'] = weight;
    }
    if (bloodPressure != null) {
      map['bloodPressure'] = bloodPressure;
    }
    return map;
  }

  PatientRegistrationModel copyWith({
    String? patientId,
    String? name,
    String? dob,
    String? gender,
    String? phone,
    String? address,
    String? bloodGroup,
    String? insuranceProvider,
    String? emergencyContact,
    double? weight,
    String? bloodPressure,
  }) {
    return PatientRegistrationModel(
      patientId: patientId ?? this.patientId,
      name: name ?? this.name,
      dob: dob ?? this.dob,
      gender: gender ?? this.gender,
      phone: phone ?? this.phone,
      address: address ?? this.address,
      bloodGroup: bloodGroup ?? this.bloodGroup,
      insuranceProvider: insuranceProvider ?? this.insuranceProvider,
      emergencyContact: emergencyContact ?? this.emergencyContact,
      weight: weight ?? this.weight,
      bloodPressure: bloodPressure ?? this.bloodPressure,
    );
  }
}